version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23
    steps:
      - checkout
      - run: 
          command: | 
            cd wordswithcrosses
            ./gradlew test
            ./gradlew check
            ./gradlew deviceAndroidTest 
